### ISSUE TITLE
The website in plugin.json

### ISSUE THREAD

**Issue by hlaueriksson** [CoreyHayward/PowerToys-Run-InputTyper#1]
I think that the website in `plugin.json` should point to this repo (https://github.com/CoreyHayward/PowerToys-Run-InputTyper)

https://github.com/CoreyHayward/PowerToys-Run-InputTyper/blob/2c41f878d48a5b4e46f94be4df4655162c204fcc/Community.PowerToys.Run.Plugin.InputTyper/plugin.json#L9

I don't know where the website is used in PowerToys, but I think is a nice touch point to the source code.

**Comment by CoreyHayward** [comment]
@hlaueriksson Have updated plugin.json to point to the repo!
