### ISSUE TITLE
Visual Studio requirement

### ISSUE THREAD

**Issue by hlaueriksson** [CoreyHayward/PowerToys-Run-InputTyper#2]
Is Visual Studio really a requirement for running the plugin?

https://github.com/CoreyHayward/PowerToys-Run-InputTyper/blob/2c41f878d48a5b4e46f94be4df4655162c204fcc/README.md?plain=1#L9

**Comment by CoreyHayward** [comment]
@hlaueriksson Yeah, good point have removed this from the README.
