### ISSUE TITLE
The ARM64 libs

### ISSUE THREAD

**Issue by hlaueriksson** [CoreyHayward/PowerToys-Run-InputTyper#4]
Hi @CoreyHayward

I'm researching how to add support for ARM64 when developing a PowerToys Run plugin.

How did you get the DLLs in the [ARM64](https://github.com/CoreyHayward/PowerToys-Run-InputTyper/tree/main/Community.PowerToys.Run.Plugin.InputTyper/Libs/ARM64) folder?

Did you build them yourself or do you have an ARM64 installation of PowerToys?

**Comment by CoreyHayward** [comment]
Hey! 

Yes, was a case of building the projects in the PowerToys repo for ARM64 and taking the dlls from the build output.

**Comment by hlaueriksson** [comment]
Thanks for letting me know!
