### ISSUE TITLE
Examples for a community plugin checklist

### ISSUE THREAD

**Issue by hlaueriksson** [CoreyHayward/PowerToys-Run-InputTyper#5]
Hi @CoreyHayward

This repo is a great blueprint on how to build community plugins.

I created a proposal for a community plugin checklist in the `awesome-powertoys-run-plugins` repo:

- https://github.com/hlaueriksson/awesome-powertoys-run-plugins/pull/17

The checklist has examples of this repo. Is that OK with you?

**Comment by hlaueriksson** [comment]
I faked the folder name `Community.PowerToys.Run.Plugin.InputTyper` in the zip file.

What do you think about giving the folder in the zip file the same name as the plugin `AssemblyName`?

**Comment by CoreyHayward** [comment]
Hi @hlaueriksson

More than happy for you to use examples of this repo in the checklist!

I'll take a look through your PR and give some feedback!
